import type { BreathingExercise } from '@/types'

export const breathingExercises: BreathingExercise[] = [
  {
    id: 'rustig-ademen',
    name: 'Rustig ademen',
    description: 'Een zachte, kalme ademhaling om tot rust te komen.',
    instructions: {
      whatFor: 'Om je zenuwstelsel te kalmeren en spanning los te laten.',
      inhale: 'Adem langzaam in door je neus gedurende 4 seconden.',
      exhale: 'Adem langzaam uit door je mond gedurende 6 seconden.',
      noseOrMouth: 'Inademen door de neus, uitademen door de mond.',
      belly: 'Laat je buik zachtjes uitzetten bij het inademen.',
      shoulders: 'Houd je schouders laag en ontspannen.',
      holdBreath: 'Niet vasthouden, adem vloeiend door.',
      safetyCue: 'Adem op je eigen tempo. Stop als je duizelig wordt.',
    },
    phases: [
      { type: 'inhale', duration: 4, label: 'Inademen', bodyFocus: 'Buik uitzetten', howToBreathe: 'Door de neus', whatsNext: 'Uitademen' },
      { type: 'exhale', duration: 6, label: 'Uitademen', bodyFocus: 'Buik ontspannen', howToBreathe: 'Door de mond', whatsNext: 'Inademen' },
    ],
  },
  {
    id: 'langer-uitademen',
    name: 'Langer uitademen',
    description: 'Adem diep vanuit je buik en adem langer uit voor diepe ontspanning.',
    instructions: {
      whatFor: 'Voor diepe ontspanning en om stress te verminderen.',
      inhale: 'Adem diep in door je neus gedurende 4 seconden, vul je buik volledig.',
      exhale: 'Adem langzaam uit door je mond gedurende 7 seconden.',
      noseOrMouth: 'Inademen door de neus, uitademen door de mond.',
      belly: 'Laat je buik zo ver mogelijk uitzetten bij het inademen. Leg eventueel een hand op je buik.',
      shoulders: 'Laat je schouders niet meebewegen, alleen je buik beweegt.',
      holdBreath: 'Houd 2 seconden vast na het inademen.',
      safetyCue: 'Ga op je eigen ritme. Bij duizeligheid, adem normaal.',
    },
    phases: [
      { type: 'inhale', duration: 4, label: 'Inademen', bodyFocus: 'Buik volledig vullen', howToBreathe: 'Door de neus', whatsNext: 'Vasthouden' },
      { type: 'hold', duration: 2, label: 'Vasthouden', bodyFocus: 'Buik vol houden', howToBreathe: 'Adem vasthouden', whatsNext: 'Uitademen' },
      { type: 'exhale', duration: 7, label: 'Uitademen', bodyFocus: 'Buik leeg laten lopen', howToBreathe: 'Door de mond', whatsNext: 'Inademen' },
    ],
  },
  {
    id: 'rust-na-spanning',
    name: 'Rust na spanning',
    description: 'Vier gelijke fasen: in — vast — uit — vast. Kalm en gestructureerd.',
    instructions: {
      whatFor: 'Om focus te vinden en je gedachten te ordenen.',
      inhale: 'Adem in gedurende 4 seconden.',
      exhale: 'Adem uit gedurende 4 seconden.',
      noseOrMouth: 'Zowel in- als uitademen door de neus.',
      belly: 'Rustige buikademing, niet te diep forceren.',
      shoulders: 'Ontspannen, niet optrekken.',
      holdBreath: 'Houd 4 seconden vast na het inademen en na het uitademen.',
      safetyCue: 'Je kunt de telduur verlagen als 4 seconden te lang voelt.',
    },
    phases: [
      { type: 'inhale', duration: 4, label: 'Inademen', bodyFocus: 'Buik vullen', howToBreathe: 'Door de neus', whatsNext: 'Vasthouden' },
      { type: 'hold', duration: 4, label: 'Vasthouden', bodyFocus: 'Stil blijven', howToBreathe: 'Adem vasthouden', whatsNext: 'Uitademen' },
      { type: 'exhale', duration: 4, label: 'Uitademen', bodyFocus: 'Buik legen', howToBreathe: 'Door de neus', whatsNext: 'Vasthouden' },
      { type: 'hold', duration: 4, label: 'Vasthouden', bodyFocus: 'Stil blijven', howToBreathe: 'Adem vasthouden', whatsNext: 'Inademen' },
    ],
  },
  {
    id: 'rustig-focussen',
    name: 'Rustig focussen',
    description: 'De 4-7-8 methode: diep inademen, vasthouden, lang uitademen.',
    instructions: {
      whatFor: 'Voor het slapengaan of bij sterke spanning.',
      inhale: 'Adem in door je neus gedurende 4 seconden.',
      exhale: 'Adem langzaam uit door je mond gedurende 8 seconden met een zacht blazend geluid.',
      noseOrMouth: 'Inademen door de neus, uitademen door de mond.',
      belly: 'Buik laten uitzetten bij het inademen.',
      shoulders: 'Volledig ontspannen.',
      holdBreath: 'Houd je adem 7 seconden vast na het inademen.',
      safetyCue: 'Start met kortere tellen als 7 seconden vasthouden te lang is.',
    },
    phases: [
      { type: 'inhale', duration: 4, label: 'Inademen', bodyFocus: 'Buik vullen', howToBreathe: 'Door de neus', whatsNext: 'Vasthouden' },
      { type: 'hold', duration: 7, label: 'Vasthouden', bodyFocus: 'Adem binnenhouden', howToBreathe: 'Adem vasthouden', whatsNext: 'Uitademen' },
      { type: 'exhale', duration: 8, label: 'Uitademen', bodyFocus: 'Alles loslaten', howToBreathe: 'Door de mond, zacht blazen', whatsNext: 'Inademen' },
    ],
  },
  {
    id: 'in-vast-ritme',
    name: 'In een vast ritme ademen',
    description: 'Snelle, gelijkmatige ademhaling om je energie op te bouwen.',
    instructions: {
      whatFor: 'Om wakker te worden, energie te krijgen en alert te zijn.',
      inhale: 'Krachtig inademen door de neus gedurende 2 seconden.',
      exhale: 'Krachtig uitademen door de neus gedurende 2 seconden.',
      noseOrMouth: 'Alles door de neus.',
      belly: 'Actieve buikbeweging: buik in bij uitademen, buik uit bij inademen.',
      shoulders: 'Stil en ontspannen.',
      holdBreath: 'Niet vasthouden.',
      safetyCue: 'Niet doen bij zwangerschap of hoge bloeddruk. Stop bij duizeligheid.',
    },
    phases: [
      { type: 'inhale', duration: 2, label: 'Inademen', bodyFocus: 'Buik krachtig vullen', howToBreathe: 'Krachtig door de neus', whatsNext: 'Uitademen' },
      { type: 'exhale', duration: 2, label: 'Uitademen', bodyFocus: 'Buik krachtig intrekken', howToBreathe: 'Krachtig door de neus', whatsNext: 'Inademen' },
    ],
  },
  {
    id: 'om-en-om',
    name: 'Om en om door je neus ademen',
    description: 'Afwisselend links en rechts ademen voor innerlijke balans.',
    isAlternateNostril: true,
    instructions: {
      whatFor: 'Om de linker- en rechterhersenhelft in balans te brengen en innerlijke rust te vinden.',
      inhale: 'Adem in door één neusgat gedurende 4 seconden.',
      exhale: 'Adem uit door het andere neusgat gedurende 4 seconden.',
      noseOrMouth: 'Alleen door de neus, afwisselend links en rechts.',
      belly: 'Rustige buikademhaling.',
      shoulders: 'Ontspannen.',
      holdBreath: 'Kort vasthouden (2 seconden) bij het wisselen.',
      handPosition: 'Gebruik je rechterhand. Duim op het rechter neusgat, ringvinger op het linker neusgat. Wissel per fase.',
      safetyCue: 'Adem rustig. Bij verkoudheid of verstopte neus is deze oefening niet geschikt.',
    },
    phases: [
      { type: 'inhale-left', duration: 4, label: 'Inademen links', bodyFocus: 'Linker neusgat open', howToBreathe: 'Door linker neusgat', whatsNext: 'Vasthouden' },
      { type: 'hold', duration: 2, label: 'Vasthouden', bodyFocus: 'Beide dicht', howToBreathe: 'Adem vasthouden', whatsNext: 'Uitademen rechts' },
      { type: 'exhale-right', duration: 4, label: 'Uitademen rechts', bodyFocus: 'Rechter neusgat open', howToBreathe: 'Door rechter neusgat', whatsNext: 'Inademen rechts' },
      { type: 'inhale-right', duration: 4, label: 'Inademen rechts', bodyFocus: 'Rechter neusgat open', howToBreathe: 'Door rechter neusgat', whatsNext: 'Vasthouden' },
      { type: 'hold', duration: 2, label: 'Vasthouden', bodyFocus: 'Beide dicht', howToBreathe: 'Adem vasthouden', whatsNext: 'Uitademen links' },
      { type: 'exhale-left', duration: 4, label: 'Uitademen links', bodyFocus: 'Linker neusgat open', howToBreathe: 'Door linker neusgat', whatsNext: 'Inademen links' },
    ],
  },
]

export const durationChoices = [
  { label: '1 min', value: 60 },
  { label: '2 min', value: 120 },
  { label: '3 min', value: 180 },
  { label: '4 min', value: 240 },
  { label: '5 min', value: 300 },
]
